Meal plan UI design ip 106
pratyushashukla/IP-FE pull request #30
Opened 2024-11-08 15:53 UTC by khanalsir

This is the UI for Meal Management. It includes Adding and Updating Meal Plan along with the route
The apis are not ready so the api integration is remaining. I have populated dummy data

2024-11-08 19:47 UTC, suraj2597 approved these changes

2024-11-09 02:27 UTC, pratyushashukla requested changes
I checked the UI, which looks good but as per the communication with Ali APIs are almost ready to be pushed so waiting to see the page with integration itself to get better understanding of the page and functionality , all together

2024-11-09 02:31 UTC, Bluwzy approved these changes
The API's are pushed in the backend repository, please review and approve. UI looks good, thank you

2024-11-10 13:50 UTC, suraj2597 approved these changes

2024-11-11 19:38 UTC, merged